/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HalkhataRouteImport } from './routes/halkhata'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubmitReportRouteImport } from './routes/api.submit-report'

const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HalkhataRoute = HalkhataRouteImport.update({
  id: '/halkhata',
  path: '/halkhata',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitReportRoute = ApiSubmitReportRouteImport.update({
  id: '/api/submit-report',
  path: '/api/submit-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/halkhata': typeof HalkhataRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/api/submit-report': typeof ApiSubmitReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/halkhata': typeof HalkhataRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/api/submit-report': typeof ApiSubmitReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/halkhata': typeof HalkhataRoute
  '/privacy': typeof PrivacyRoute
  '/rates': typeof RatesRoute
  '/api/submit-report': typeof ApiSubmitReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/halkhata' | '/privacy' | '/rates' | '/api/submit-report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/halkhata' | '/privacy' | '/rates' | '/api/submit-report'
  id:
    | '__root__'
    | '/'
    | '/halkhata'
    | '/privacy'
    | '/rates'
    | '/api/submit-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HalkhataRoute: typeof HalkhataRoute
  PrivacyRoute: typeof PrivacyRoute
  RatesRoute: typeof RatesRoute
  ApiSubmitReportRoute: typeof ApiSubmitReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halkhata': {
      id: '/halkhata'
      path: '/halkhata'
      fullPath: '/halkhata'
      preLoaderRoute: typeof HalkhataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-report': {
      id: '/api/submit-report'
      path: '/api/submit-report'
      fullPath: '/api/submit-report'
      preLoaderRoute: typeof ApiSubmitReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HalkhataRoute: HalkhataRoute,
  PrivacyRoute: PrivacyRoute,
  RatesRoute: RatesRoute,
  ApiSubmitReportRoute: ApiSubmitReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
